# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Intel.FortranCompiler
PackageVersion: 2025.1.1
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: -s -a --silent --eula accept
  SilentWithProgress: -s -a --silent --eula accept
ExpectedReturnCodes:
- InstallerReturnCode: 1001
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 1002
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
InstallLocationRequired: false
RequireExplicitUpgrade: true
Installers:
- Architecture: x64
  InstallerUrl: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/20fc9768-cb87-4aaa-adf8-6c83a5d8e8b4/intel-fortran-compiler-2025.1.1.11_offline.exe
  InstallerSha256: 5E3422654080B0EA799482C7BAF08C75FD6A37B6246E972D41BE72E6507986B9
ManifestType: installer
ManifestVersion: 1.9.0
