# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: WHTA.Tamara
PackageVersion: 2025.3.1.2
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: -mode silent -agreeToLicense yes
  SilentWithProgress: -mode silent -agreeToLicense yes
UpgradeBehavior: install
FileExtensions:
- mat
- tam
- unv
- uff
- hdf
- pti
- wav
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
RequireExplicitUpgrade: true
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://download.tamara.app/2025.3.1.2/installer.exe
  InstallerSha256: E9A8593CCECA469D3C86CF4A9ACD194A3AC69A96EB25E8EAF6A54AB9AF0DB834
  AppsAndFeaturesEntries:
  - DisplayName: Tamara
    Publisher: NVH Group AB
    ProductCode: Tamara
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-09-01
